import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export interface PatientLookup {
  id: number;
  firstName: string;
  lastName: string;
  dni: string;
}

export interface QueueRegistrationResponse {
  /** Queue code generated by the backend (mapped from backend `publicCode`). */
  queueNumber: string;
}

@Injectable({ providedIn: 'root' })
export class TotemService {
  private http = inject(HttpClient);

  lookupPatientByDni(dni: string): Observable<PatientLookup> {
    return this.http.get<PatientLookup>(`/api/v1/analitica/patients/by-dni/${dni}`);
  }

  registerQueueEntry(input: { patientId: number; branchId: number }): Observable<QueueRegistrationResponse> {
    return this.http
      .post<{ publicCode: string }>('/api/v1/turnos/queue', {
        nationalId: null,
        patientId: input.patientId,
        branchId: input.branchId,
        hasAppointment: false,
      })
      .pipe(map((res) => ({ queueNumber: res.publicCode })));
  }
}
